gui:
  language: 'en'
  mouseEvents: false
  scrollHeight: 14
  filterMode: 'fuzzy'
  showCommandLog: false

keybinding:
  commits:
    moveDownCommit: ["<alt+j>", "<alt+down>"]
    moveUpCommit: ["<alt+k>", "<alt+up>"]

git:
  useConfig: true
  overrideGpg: true

refresher:
  fetchInterval: 300

notARepository: 'quit'
